### ISSUE TITLE
'URLSearchParams' is undefined in IE

### ISSUE THREAD

**Issue by DakotaWray2** [michaelsoriano/sp-forms#1]
Line 331 in sp-forms.js
`        var urlParams = new URLSearchParams(window.location.search);`
[URLSearchParams is unsupported in IE.](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams)

[I have found a possible fix here.](https://stackoverflow.com/questions/45758837/script5009-urlsearchparams-is-undefined-in-ie-11)

**Comment by michaelsoriano** [comment]
thank you @DakotaWray2 . it should be fixed now. Please download again.
