### ISSUE TITLE
Lists without attachment requirement

### ISSUE THREAD

**Issue by DakotaWray2** [michaelsoriano/sp-forms#2]
Michael,
When not including an attachment form-group I receive the error "Cannot read property 'files' of undefined.
I can get around this by adding the attachment form-group and adding the inline style of display:none;.
You may want to amend sp-forms.js to remove this behavior, or detail it in the documentation.

Thank you for the great resource. I have learned a lot from your blog/repositories.

**Comment by michaelsoriano** [comment]
@DakotaWray2 - should be fixed now. thank you as well.

**Comment by DakotaWray2** [comment]
Thanks, that fixed the issue.
