### ISSUE TITLE
Unable to convert primitive value of blank string values 

### ISSUE THREAD

**Issue by DakotaWray2** [michaelsoriano/sp-forms#3]
Michael,
I came across an issue when I'm integrating many fields but most of them not being required. 
I receive the following error.

> Cannot convert a primitive value to the expected type 'Edm.Double'. See the inner exception for more details.

Because I have front end validation and do not care if i POST the blank values i inserted the following @ line 109 in sp-forms.js

`	  $.each(itemObj, function(key, value){
		if (value === "" || value === null){
        delete itemObj[key];
		}
		});`

**Comment by michaelsoriano** [comment]
The SharePoint list fields can only be text for now. It doesn't support any other field types.
